### ISSUE TITLE
sitemap 插件的功能清单

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-sitemap#1]
## 功能要求

1. 插件需要支持添加 `/sitemap.xml` 路由。
2. 提供 sitemap 的渲染模板。
4. 根据系统内的文章/分类/标签等资源 和 https://www.sitemaps.org/protocol.html 生成符合预期的格式。

**Comment by guqing** [comment]
see https://github.com/halo-sigs/plugin-sitemap/releases/tag/v1.0.0-alpha.1
