### ISSUE TITLE
需要帮助：生成的站点地图域名为 localhost

### ISSUE THREAD

**Issue by doubleki7461** [halo-sigs/plugin-sitemap#9]
使用 sitemap 插件自动生成站点地图域名为 localhost，提交到 Google Console Search 后报错

![image](https://github.com/halo-sigs/plugin-sitemap/assets/114803508/a7d65580-48e4-4995-8e5d-317099602cc6)

站点地图链接为：http://blog.kierankihn.com/sitemap.xml

在 halo 的 docker-compose.yaml 中已经正确设置了地址，但是不起作用

已经试过重启 halo，重装插件，均无效

请问如何解决

**Comment by JohnNiang** [comment]
可能还需要提供一下反向代理的配置。如果 Nginx 侧没有传递 X-Forwareded-Host 请求头的话，也可能会导致 Halo 无法获取到当前请求的 Host：`blog.kierankihn.com`。

**Comment by doubleki7461** [comment]
添加 X-Forwareded-Host 请求头后问题已经解决，感谢帮助！

**Comment by nasheep** [comment]
> 添加 X-Forwareded-Host 请求头后问题已经解决，感谢帮助！

请问如何设置？可以提供一下配置吗？谢谢！
